### ISSUE TITLE
Add user search function

### ISSUE THREAD

**Issue by alilinares** [alilinares/vinyl-zone#11]
User should be able to search for a song and/or musician. 

## Tasks
- [ ] Search algorithm 
- [ ] Capture user input 
- [ ] Process user input
- [ ] Find a matching a result
- [ ] Present Result
- [ ] Play Result
- [ ] Present error code __ on search fail
- [ ] Develop html search form
- [ ] Style the search with CSS
